language: java

services:
  - docker
env:
  - OS_TYPE=centos OS_VERSION=6 ANSIBLE_VERSION=1.9.2
jobs:
  include:
    - stage: test
      if: branch = dev
      script:
        - cd simple-api/
        - mvn clean verify
        - cd ../
    - stage: publish_api
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-api ./simple-api
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-api $DOCKERHUB_USER/tp-api:1.1
        - docker push $DOCKERHUB_USER/tp-api
    - stage: publish_data
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-db ./database
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-db $DOCKERHUB_USER/tp-db:1.1
        - docker push $DOCKERHUB_USER/tp-db
    - stage: publish_httpd
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-httpd ./httpd
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-httpd $DOCKERHUB_USER/tp-httpd:1.1
        - docker push $DOCKERHUB_USER/tp-httpd
    - stage: deploy
      #   if: branch = master
      addons:
        ssh_known_hosts: emeline-garo.takima.io
      install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo apt-add-repository --yes --update ppa:ansible/ansible
        - sudo apt install ansible
        - ansible-galaxy collection install ericsysmin.docker
      script:
        - ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
