language: java

services:
  - docker

jobs:
  include:
    - stage: test
    if: branch = dev
      script:
        - cd simple-api/
        - mvn clean verify
        - cd ../
    - stage: publish_api
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-api ./simple-api
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-api $DOCKERHUB_USER/tp-api:1.1
        - docker push $DOCKERHUB_USER/tp-api
    - stage: publish_data
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-db ./database
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-db $DOCKERHUB_USER/tp-db:1.1
        - docker push $DOCKERHUB_USER/tp-db
    - stage: publish_httpd
      if: branch = dev
      script:
        - docker build -t $DOCKERHUB_USER/tp-httpd ./httpd
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker tag $DOCKERHUB_USER/tp-httpd $DOCKERHUB_USER/tp-httpd:1.1
        - docker push $DOCKERHUB_USER/tp-httpd
    - stage: deploy
    #   if: branch = master
      addons:
        ssh_known_hosts: emeline-garo.takima.io
      install:
        - sudo yum install ansible
        - sansible-galaxy collection install ericsysmin.docker
      script:
        - openssl aes-256-cbc -K $encrypted_ec0015db4ac4_key -iv $encrypted_ec0015db4ac4_iv -in id_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml    
   